--- 
title: "Advanced Statistics and Data Analysis: Korean Version"
subtitle: "중급 통계와 데이터 관리: 한글판"
author: "Sanghoon Park"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
header-includes:
  - \usepackage{kotex}
  - \usepackage{amsmath,amsthm}
  - \usepackage{graphicx}
output: 
  pdf_document: 
    latex_engine: xelatex
    fig_height: 6
    fig_width: 10
    fig_caption: yes
    toc: no
documentclass: book
geometry: margin=1in
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
mainfont: NanumGothic
urlcolor: blue
---

# Prerequisites

만약 정치사상을 전공하거나, 100\% 게임이론으로만 현상을 분석하고자 하는 사람이 아니라면, 통계분석 기법은 사회과학자에게 있어서 더 이상은 피할 수 없는, 필수적으로 배워야하는 것이 현실입니다. 이 자료, 중급통계 통계와 데이터관리는 사회과학 연구에 있어서 필요한 공식적/비공식적인 통계학적 지식들을 사회과학적 예제를 대상으로 적용하여 보고자 하는 데 목적이 있습니다. 주로, 이 자료는 사회과학자들이 사용하는 거의 모든 통계기법들에 연계되어 있는 교차점---선형회귀을 중심으로 전개됩니다.

날이 갈수록 사회과학 분야에서 연구를 수행하는 데 복잡한 통계학적 소양을 요구하는 경향이 심화되고 있는 것이 사실입니다. 상관관계를 분석하는 것에 그치던 1970년대, 단순회귀분석으로 충분했던 1980년대, 가능도(likelihood)를 이용한 접근법이 만연했던 1990년대와는 달리 2000년대부터는 구조방정식(structural equation), 베이지안 통계 추론(Baysesian statistical inference), 그리고 인과적 추론(causal inference)가 주요한 방법론으로 떠올랐고, 이제는 필연적으로 숙지해야 하는 방법이 되었습니다. 최근에 들어서는 머신러닝 접근법이 부상하고 있고, 오늘 날 상대적으로 낮은 순위에 머물러있는 하위분과에 대한 저널들까지도 1990년대의 사회과학자들에게는 굉장히 생소할법한 통계기법들이 사용된 연구결과들을 수록하고는 합니다.

이 자료는 경험적 사회과학연구를 수행하기 위한 도구로서 통계기법을 학습하도록 돕는 데 목적이 있습니다. 최근의, 그리고 실질적인 측면에서 통계기법을 살펴보는 데 초점을 두고 있으며, 자료는 선형회귀모델의 기초를 소개하는 것에서 시작됩니다.

이 자료를 통해서 갖출 수 있는 소양으로 기대되는 것은 다음과 같습니다.

  + 선형회귀모델의 기초를 이해할 수 있게 될 것입니다.
  + 추론의 도구로서 선형회귀모델을 사용한 사회과학 연구들을 읽고 이해할 수 있게 될 것입니다.
  + 전통적인 방법, 현대적인 방법을 통해 추론하는 법을 배울 수 있게 될 것입니다.
  + 나아가 데이터를 보여주기 위해 유용한 그래픽을 활용할 수 있게 될 것입니다.
  + **R**을 이용하여 데이터를 관리 및 분석할 수 있게 될 것입니다.
  
이 Git의 자료들은 다음의 자료에 기초하여 작성되었습니다.

  + Jeffrey M. Wooldridge’s Introductory Econometrics: A Modern Approach, 5th (or later) edition.
  
같은 자료에 접근하고 이를 다루는 여러 가지 방법들이 존재합니다. 따라서 위의 자료 말고도 여러 자료들을 보조적으로 활용하여 선형회귀모델을 이해할 수 있습니다. 

  + Andrew Gelman \& Jennifer Hill, Data Analysis Using Regression and Multilevel/ Hierarchical Models.
  + HadleyWickham, ggplot2: Elegant Graphics for Data Analysis.
  + Fumio Hayashi, Econometrics.
  + Joshua D. Angrist \& J\"{o}rn-Steffen Pischke, Mostly Harmless Econometrics.
  + William H. Greene, Econometric Analysis.
  + Peter Kennedy, A Guide to Econometrics.
  + Damodar Gujarati \& Dawn Porter, Basic Econometrics.
  
이 자료에서 통계적 문제들은 **R**을 이용해서 살펴봅니다. **R**은 일단 하나의 언어라고 생각할 수 있습니다. **R** 자체로도 함수들을 이용해 우리가 원하는 분석을 할 수 있겠지만, 굉장히 편리하고 유용한 플랫폼을 통해서 보다 용이하게, 편리하게 **R**을 사용할 수 있습니다. 바로 *RStudio*입니다. *RStudio*는 Graphical User Interface(GUI)로 **R**을 좀 더 직관적으로 사용하는 데 도움을 줍니다.

  + **R**을 다운로드 하시려면 [여기](https://cloud.r-project.org/)
  + **R**을 설치하고 나서 플랫폼으로 설치할 [RStudio](https://www.rstudio.com/products/rstudio/download/#download)

```{r, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(error = FALSE, warning = FALSE, message = FALSE,
                      fig.height = 3, fig.width = 6, fig.align = 'center')
```
